"use client";

type Props = {
    name: string;
    generatedBy: string;
    createdAt: string;
    maskedKey: string;
    onEdit: () => void;
    onDelete: () => void;
};

export default function ApiKeyCard({
    name,
    generatedBy,
    createdAt,
    maskedKey,
    onEdit,
    onDelete,
}: Props) {
    return (
        <div className="rounded-xl border border-gray-200 bg-white p-6">
            {/* Header */}
            <div className="flex flex-col gap-2 md:flex-row md:items-start md:justify-between">
                <div>
                    <h3 className="text-xl font-semibold">{name}</h3>

                    <div className="mt-2 flex flex-col gap-1 text-sm text-gray-500 sm:flex-row sm:items-center sm:gap-6">
                        <p>
                            <span className="font-medium text-gray-700">
                                Generated By:
                            </span>{" "}
                            {generatedBy}
                        </p>

                        <p>
                            {new Date(createdAt).toLocaleDateString()}{" "}
                            {new Date(createdAt).toLocaleTimeString()}
                        </p>
                    </div>
                </div>

                {/* Future Status Badge */}
                {/* Active */}
            </div>

            {/* API Key */}
            <div className="mt-6">
                <label className="mb-2 block text-sm font-medium text-gray-700">
                    API Key
                </label>

                <div className="rounded-lg border bg-gray-50 px-4 py-3">
                    <code className="break-all text-sm">
                        {maskedKey}
                    </code>
                </div>
            </div>

            {/* Footer */}
            <div className="mt-6 flex flex-col gap-3 sm:flex-row sm:justify-end">
                <button
                    onClick={onEdit}
                    className="rounded-lg border px-5 py-2"
                >
                    Edit
                </button>

                <button
                    onClick={onDelete}
                    className="rounded-lg border border-red-300 px-5 py-2 text-red-600"
                >
                    Delete
                </button>
            </div>
        </div>
    );
}