export const NOTIFICATION_TYPES = {
  TASK_ASSIGNED: "TASK_ASSIGNED",
  TASK_UPDATED: "TASK_UPDATED",
  TASK_REASSIGNED: "TASK_REASSIGNED",
  TASK_COMPLETED: "TASK_COMPLETED",

  TRACKING_STARTED: "TRACKING_STARTED",
  TRACKING_STOPPED: "TRACKING_STOPPED",
  TRACKING_WARNING: "TRACKING_WARNING",
  IDLE_WARNING: "IDLE_WARNING",

  SHIFT_STARTED: "SHIFT_STARTED",
  SHIFT_ENDED: "SHIFT_ENDED",
  SHIFT_UPDATED: "SHIFT_UPDATED",

  MANUAL_TIME_SUBMITTED: "MANUAL_TIME_SUBMITTED",
  MANUAL_TIME_APPROVED: "MANUAL_TIME_APPROVED",
  MANUAL_TIME_REJECTED: "MANUAL_TIME_REJECTED",

  USER_INVITED: "USER_INVITED",
  USER_ADDED: "USER_ADDED",
  ROLE_CHANGED: "ROLE_CHANGED",

  REPORT_READY: "REPORT_READY",
  REPORT_FAILED: "REPORT_FAILED",

  SYSTEM: "SYSTEM",
};